
export const productData = [
  {
    id: 1,
    name: "Hydrating Rose Facial Serum",
    brand: "Glow Labs",
    category: "Skincare",
    price: 49.99,
    rating: 4.8,
    image: "/product-1.jpg",
    description:
      "Intensive hydrating serum with rose water and hyaluronic acid",
    details:
      "This luxurious facial serum combines the power of Damascus rose water with triple-weight hyaluronic acid for deep hydration. Perfect for all skin types, especially dry and sensitive skin.",
    ingredients: ["Rose Water", "Hyaluronic Acid", "Vitamin E", "Glycerin"],
    usage: "Apply 2-3 drops to clean, damp skin morning and evening.",
  },
  {
    id: 2,
    name: "Vitamin C Brightening Cream",
    brand: "Pure Beauty",
    category: "Skincare",
    price: 38.99,
    rating: 4.7,
    image: "/product-2.jpg",
    description: "Brightening cream with 20% Vitamin C complex",
    details:
      "Advanced brightening formula with 20% stabilized Vitamin C, ferulic acid, and vitamin E. Helps fade dark spots and improve skin radiance.",
    ingredients: ["Vitamin C", "Ferulic Acid", "Vitamin E", "Niacinamide"],
    usage: "Apply a small amount to face and neck every morning.",
  },
  {
    id: 3,
    name: "Silk Protein Hair Mask",
    brand: "Hair Luxe",
    category: "Haircare",
    price: 34.99,
    rating: 4.9,
    image: "/product-3.jpg",
    description: "Deep conditioning hair mask with silk proteins",
    details:
      "Intensive hair treatment mask enriched with silk proteins and keratin. Repairs damaged hair and adds incredible shine and softness.",
    ingredients: ["Silk Proteins", "Keratin", "Argan Oil", "Panthenol"],
    usage: "Apply to damp hair, leave for 15-20 minutes, then rinse.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 5,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-5.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id:6,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-6.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 7,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-7.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 8,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-8.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 9,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-9.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 10,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-10.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 11,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-11.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 12,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-12.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 13,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-13.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 14,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-14.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 15,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-15.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 16,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-16.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 17,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-17.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 18,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-18.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 19,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-19.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 20,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-20.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 21,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-21.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 22,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-22.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 23,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-23.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 24,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-24.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 25,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-25.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 26,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-26.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 27,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-27.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 28,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-28.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 29,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-29.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 30,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-30.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 31,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-31.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 32,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-32.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 33,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-33.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 34,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-34.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 35,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-35.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 36,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-36.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 37,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-37.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 38,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-38.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 39,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-39.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 40,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-40.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 41,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-41.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 42,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-42.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 43,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-43.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 44,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-44.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 45,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-45.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 46,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-46.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 47,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-47.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 48,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-48.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 49,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-49.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 50,
    name: "Rose Quartz Facial Roller",
    brand: "Crystal Beauty",
    category: "Tools",
    price: 29.99,
    rating: 4.7,
    image: "/product-5.jpg",
    description: "Genuine rose quartz facial massage tool",
    details:
      "100% authentic rose quartz roller that helps reduce puffiness and promote lymphatic drainage. Perfect for morning skincare routine.",
    ingredients: ["Genuine Rose Quartz"],
    usage:
      "Use gentle rolling motions on clean skin or over skincare products.",
  },
];