export const productData = [
  {
    "name": "Hydrating Rose Facial Serum",
    "brand": "Glow Labs",
    "category": "Skincare",
    "price": 49.99,
    "rating": 4.8,
    "images": [
      { "url": "/product-1.jpg" },
      { "url": "/product-1.jpg" },
      { "url": "/product-1.jpg" },
    ],
    "description":
      "Intensive hydrating serum with rose water and hyaluronic acid",
    "details":
      "This luxurious facial serum combines the power of Damascus rose water with triple-weight hyaluronic acid for deep hydration. Perfect for all skin types, especially dry and sensitive skin.",
    "ingredients": ["Rose Water", "Hyaluronic Acid", "Vitamin E", "Glycerin"],
    "usage": "Apply 2-3 drops to clean, damp skin morning and evening.",
  },
  {
    "name": "Vitamin C Brightening Cream",
    "brand": "Pure Beauty",
    "category": "Skincare",
    "price": 38.99,
    "rating": 4.7,
    "images": [
      { "url": "/product-2.jpg" },
      { "url": "/product-2.jpg" },
      { "url": "/product-2.jpg" },
      { "url": "/product-2.jpg" },
    ],
    "description": "Brightening cream with 20% Vitamin C complex",
    "details":
      "Advanced brightening formula with 20% stabilized Vitamin C, ferulic acid, and vitamin E. Helps fade dark spots and improve skin radiance.",
    "ingredients": ["Vitamin C", "Ferulic Acid", "Vitamin E", "Niacinamide"],
    "usage": "Apply a small amount to face and neck every morning.",
  },
  {
    "name": "Silk Protein Hair Mask",
    "brand": "Hair Luxe",
    "category": "Haircare",
    "price": 34.99,
    "rating": 4.9,
    "images": [
      { "url": "/product-3.jpg" },
      { "url": "/product-3.jpg" },
      { "url": "/product-3.jpg" },
      { "url": "/product-3.jpg" },
    ],
    "description": "Deep conditioning hair mask with silk proteins",
    "details":
      "Intensive hair treatment mask enriched with silk proteins and keratin. Repairs damaged hair and adds incredible shine and softness.",
    "ingredients": ["Silk Proteins", "Keratin", "Argan Oil", "Panthenol"],
    "usage": "Apply to damp hair, leave for 15-20 minutes, then rinse.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-4.jpg" },
      { "url": "/product-4.jpg" },
      { "url": "/product-4.jpg" },
      { "url": "/product-4.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-5.jpg" },
      { "url": "/product-5.jpg" },
      { "url": "/product-5.jpg" },
      { "url": "/product-5.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-6.jpg" },
      { "url": "/product-6.jpg" },
      { "url": "/product-6.jpg" },
      { "url": "/product-6.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-7.jpg" },
      { "url": "/product-7.jpg" },
      { "url": "/product-7.jpg" },
      { "url": "/product-7.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-8.jpg" },
      { "url": "/product-8.jpg" },
      { "url": "/product-8.jpg" },
      { "url": "/product-8.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-9.jpg" },
      { "url": "/product-9.jpg" },
      { "url": "/product-9.jpg" },
      { "url": "/product-9.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-10.jpg" },
      { "url": "/product-10.jpg" },
      { "url": "/product-10.jpg" },
      { "url": "/product-10.jpg" },
      { "url": "/product-10.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-11.jpg" },
      { "url": "/product-11.jpg" },
      { "url": "/product-11.jpg" },
      { "url": "/product-11.jpg" },
      { "url": "/product-11.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-12.jpg" },
      { "url": "/product-12.jpg" },
      { "url": "/product-12.jpg" },
      { "url": "/product-12.jpg" },
      { "url": "/product-12.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-13.jpg" },
      { "url": "/product-13.jpg" },
      { "url": "/product-13.jpg" },
      { "url": "/product-13.jpg" },
      { "url": "/product-13.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-14.jpg" },
      { "url": "/product-14.jpg" },
      { "url": "/product-14.jpg" },
      { "url": "/product-14.jpg" },
      { "url": "/product-14.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-15.jpg" },
      { "url": "/product-15.jpg" },
      { "url": "/product-15.jpg" },
      { "url": "/product-15.jpg" },
      { "url": "/product-15.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-16.jpg" },
      { "url": "/product-16.jpg" },
      { "url": "/product-16.jpg" },
      { "url": "/product-16.jpg" },
      { "url": "/product-16.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-17.jpg" },
      { "url": "/product-17.jpg" },
      { "url": "/product-17.jpg" },
      { "url": "/product-17.jpg" },
      { "url": "/product-17.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-18.jpg" },
      { "url": "/product-18.jpg" },
      { "url": "/product-18.jpg" },
      { "url": "/product-18.jpg" },
      { "url": "/product-18.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-19.jpg" },
      { "url": "/product-19.jpg" },
      { "url": "/product-19.jpg" },
      { "url": "/product-19.jpg" },
      { "url": "/product-19.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-20.jpg" },
      { "url": "/product-20.jpg" },
      { "url": "/product-20.jpg" },
      { "url": "/product-20.jpg" },
      { "url": "/product-20.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-21.jpg" },
      { "url": "/product-21.jpg" },
      { "url": "/product-21.jpg" },
      { "url": "/product-21.jpg" },
      { "url": "/product-21.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-22.jpg" },
      { "url": "/product-22.jpg" },
      { "url": "/product-22.jpg" },
      { "url": "/product-22.jpg" },
      { "url": "/product-22.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-23.jpg" },
      { "url": "/product-23.jpg" },
      { "url": "/product-23.jpg" },
      { "url": "/product-23.jpg" },
      { "url": "/product-23.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-24.jpg" },
      { "url": "/product-24.jpg" },
      { "url": "/product-24.jpg" },
      { "url": "/product-24.jpg" },
      { "url": "/product-24.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
  {
    "name": "Matte Velvet Foundation",
    "brand": "Glam Cosmetics",
    "category": "Makeup",
    "price": 42.99,
    "rating": 4.6,
    "images": [
      { "url": "/product-25.jpg" },
      { "url": "/product-25.jpg" },
      { "url": "/product-25.jpg" },
      { "url": "/product-25.jpg" },
      { "url": "/product-25.jpg" },
    ],
    "description": "Long-wearing matte foundation with buildable coverage",
    "details":
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    "ingredients": ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    "usage": "Apply with brush or sponge for desired coverage.",
  },
]
