
export const productData = [
  {
    id: 1,
    name: "Hydrating Rose Facial Serum",
    brand: "Glow Labs",
    category: "Skincare",
    price: 49.99,
    rating: 4.8,
    image: "/product-1.jpg",
    description:
      "Intensive hydrating serum with rose water and hyaluronic acid",
    details:
      "This luxurious facial serum combines the power of Damascus rose water with triple-weight hyaluronic acid for deep hydration. Perfect for all skin types, especially dry and sensitive skin.",
    ingredients: ["Rose Water", "Hyaluronic Acid", "Vitamin E", "Glycerin"],
    usage: "Apply 2-3 drops to clean, damp skin morning and evening.",
  },
  {
    id: 2,
    name: "Vitamin C Brightening Cream",
    brand: "Pure Beauty",
    category: "Skincare",
    price: 38.99,
    rating: 4.7,
    image: "/product-2.jpg",
    description: "Brightening cream with 20% Vitamin C complex",
    details:
      "Advanced brightening formula with 20% stabilized Vitamin C, ferulic acid, and vitamin E. Helps fade dark spots and improve skin radiance.",
    ingredients: ["Vitamin C", "Ferulic Acid", "Vitamin E", "Niacinamide"],
    usage: "Apply a small amount to face and neck every morning.",
  },
  {
    id: 3,
    name: "Silk Protein Hair Mask",
    brand: "Hair Luxe",
    category: "Haircare",
    price: 34.99,
    rating: 4.9,
    image: "/product-3.jpg",
    description: "Deep conditioning hair mask with silk proteins",
    details:
      "Intensive hair treatment mask enriched with silk proteins and keratin. Repairs damaged hair and adds incredible shine and softness.",
    ingredients: ["Silk Proteins", "Keratin", "Argan Oil", "Panthenol"],
    usage: "Apply to damp hair, leave for 15-20 minutes, then rinse.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 5,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id:6,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 4,
    name: "Matte Velvet Foundation",
    brand: "Glam Cosmetics",
    category: "Makeup",
    price: 42.99,
    rating: 4.6,
    image: "/product-4.jpg",
    description: "Long-wearing matte foundation with buildable coverage",
    details:
      "Lightweight yet full-coverage foundation that stays matte all day. Available in 40 shades for all skin tones.",
    ingredients: ["Silica", "Vitamin E", "Hyaluronic Acid", "SPF 15"],
    usage: "Apply with brush or sponge for desired coverage.",
  },
  {
    id: 5,
    name: "Rose Quartz Facial Roller",
    brand: "Crystal Beauty",
    category: "Tools",
    price: 29.99,
    rating: 4.7,
    image: "/product-5.jpg",
    description: "Genuine rose quartz facial massage tool",
    details:
      "100% authentic rose quartz roller that helps reduce puffiness and promote lymphatic drainage. Perfect for morning skincare routine.",
    ingredients: ["Genuine Rose Quartz"],
    usage:
      "Use gentle rolling motions on clean skin or over skincare products.",
  },
];