// src/app/layout.js
import { Montserrat } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/cart"; // Update the import
import { SearchProvider } from "@/context/search"; // Add this import
import { Toaster } from "sonner";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Itapelo Group LLC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-sans antialiased`}>
        <SearchProvider>
          <CartProvider>
            <Toaster richColors position="top-right" expand/>
            {children}</CartProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
